server:
  port: 8080
spring:
  application:
    name: "auth-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  paths:
    users: "/api/v1/usuarios/register"
    userByDocumentNumber: "/api/v1/usuarios/{documentNumber}"
    login: "/api/v1/login"
jwt:
  secret: mySuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
  expiration: 30

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "postgres"
    schema: "public"
    username: "postgres"
    password: "postgres"
logging:
  level:
    org.springframework.security: DEBUG
    io.jsonwebtoken: DEBUG